# Generated by Django 5.0.14 on 2026-03-29 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_portraitbooking_frame_type_and_more'),
        ('core', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='portraitbooking',
            name='reference_image_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portraitbooking_images', to='core.mediafile'),
        ),
        migrations.AddField(
            model_name='size',
            name='reference_image_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='size_images', to='core.mediafile'),
        ),
    ]
