# Generated by Django 5.0.14 on 2026-03-29 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '__first__'),
        ('shop', '0007_rename_shipping_city_order_shipping_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_images', to='core.mediafile'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productimage_images', to='core.mediafile'),
        ),
    ]
