# Generated by Django 5.0.14 on 2026-03-29 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '__first__'),
        ('newsposts', '0002_alter_newspost_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='image_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newspost_images', to='core.mediafile'),
        ),
    ]
